runtime: python37

instance_class: F1

entrypoint: gunicorn -c setup.ini tikup.wsgi

automatic_scaling:
  min_instances: 1
  max_instances: 1

env_variables:
  DB_USER: postgres
  DB_PASSWORD: misco-postgres-password
  DB_HOST: 104.197.138.130
  DB_NAME: misco-server
  ENVIRONMENT: production
  SECRET_KEY: "ecam-h@zyoo+-cq6ba4dx7ucux49wu)e!4g@)8!uuzx=6sbk0r"
  GITHUB_TOKEN: 9ff6253fcd558f10270d312688017bf8a984b856
  GOOGLE_APPLICATION_CREDENTIALS: google-permissions/app-engine-default-service-account.json

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto